### PR TITLE
Wrap outbound client thread stream exceptions

### LINKED ISSUE #102: An exception on an RPC call causes the whole connection to fail
I _think_ that this is a limitation of `http2`, but I do not know for sure. One potential clue I found during debugging this is that perhaps things go wrong in `http2` is we throw an exception in `outboundTrailersMaker`, but I don't know if that is a red herring or not.

To reproduce this, change `clientGlobal` in `Test.Driver.Dialogue.Execution` to always use a single connection, and plenty of test cases will start to fail.

### PR DESCRIPTION
**Pull request by FinleyMcIlwaine**
Unlike the server inbound/outbound and client outbound threads, `http2` is aware of the client outbound thread. If the server disconnects, there is a race between the `http2`-thrown exception and the exception that will come from `grapesy` attempting to read. No matter who wins that race, we want to mark the exception with `ServerDisconnected`.

Also add sanity check tests for handling of exceptions/disconnects of client/server while there are open connections with ongoing concurrent calls.

Resolves #102

### CODE REVIEW

File: test-grapesy/Test/Sanity/Disconnect.hs [hunk 1]
```diff
@@ -0,0 +1,288 @@
...
+              | otherwise
+              = Client.ReconnectAfter $ do
+                  threadDelay 10000
+                  return $ go (n + 1)
+
+        connParams :: Client.ConnParams
+        connParams = def { Client.connReconnectPolicy = reconnectPolicy }
+
+    Client.withConnection connParams serverAddress $ \conn -> do
+      -- Make 50 concurrent calls. 49 of them sending infinite messages. One
```
Comment (edsko) [inline test-grapesy/Test/Sanity/Disconnect.hs:194]: Some duplication here with the first test. Not a huge deal, but I actually think that abstracting this out would not just avoid the duplication but also clarify the test.

File: test-grapesy/Test/Sanity/Exception.hs [hunk 2]
```diff
@@ -0,0 +1,196 @@
...
+--
+-- These tests check for the behavior described in
+-- <https://github.com/well-typed/grapesy/issues/102>. In particular, there are
+-- two conditions that should hold when an exception occurs in the scope of a
+-- call (on either the server or client, e.g. inside either 'mkRpcHandler' or
+-- 'withRPC'):
+--
+-- 1. Other ongoing calls on that connection are not terminated, and
+-- 2. future calls are still possible.
+module Test.Sanity.Exception where
```
Comment (edsko) [inline test-grapesy/Test/Sanity/Exception.hs:14]: This comment seems to describe only the client side of these tests?

Comment (edsko) [inline test-grapesy/Test/Sanity/Exception.hs:14]: Missing export list.

File: test-grapesy/Test/Sanity/Exception.hs [hunk 3]
```diff
@@ -0,0 +1,196 @@
...
+            predicates
+
+        -- Only one of the calls failed
+        assertEqual "" (length $ lefts results) 1
+
+        -- All others terminated with results satisfying the predicate
+        assertBool "" (all predicate $ rights results)
+
+        -- New calls still succeed
+        assertBool "" . predicate
```
Comment (edsko) [inline test-grapesy/Test/Sanity/Exception.hs:74]: Very nice, this is also a very pretty that verifies exactly what we wanted to verify :)

File: util/Network/GRPC/Util/Session/Channel.hs [hunk 4]
```diff
@@ -522,7 +522,7 @@ linkOutboundToInbound allowHalfClosed channel inbound = do
   threads, using the 'Thread' API from "Network.GRPC.Util.Thread". We are
   therefore not particularly worried about these loops being interrupted by
   asynchronous exceptions: this only happens if the threads are explicitly
-  terminated (when the corrresponding channels are closed), in which case any
+  terminated (when the corresponding channels are closed), in which case any
```
Comment (edsko) [inline util/Network/GRPC/Util/Session/Channel.hs:525]: Thanks for taking the time to fix these typos!

**Review by edsko — CHANGES_REQUESTED** [review]

File: test-grapesy/Test/Sanity/Disconnect.hs [hunk 5]
```diff
@@ -0,0 +1,288 @@
...
+test_serverDisconnect :: Assertion
+test_serverDisconnect = withTemporaryFile $ \ipcFile -> do
+    -- We use a temporary file as a very rudimentary means of inter-process
+    -- communication so the server (which runs in a separate process) can make
+    -- the client aware of the port it is assigned by the OS. This also helps us
+    -- make sure the server binds to the same port when it comes back up for
+    -- reconnect purposes.
+    let ipcWrite :: String -> IO ()
+        ipcWrite msg = do
+          writeFile ipcFile ""
```
[the remark this answers is not in the document]
Comment (FinleyMcIlwaine) [reply test-grapesy/Test/Sanity/Disconnect.hs:134]: Yes this can be removed

File: test-grapesy/Test/Sanity/Disconnect.hs [hunk 6]
```diff
@@ -0,0 +1,288 @@
...
+          writeFile ipcFile msg
+
+        ipcRead :: IO String
+        ipcRead = readFile ipcFile
+
+        ipcWaitRead :: IO String
+        ipcWaitRead = do
+          ipcRead >>= \case
+            "" -> do
+              threadDelay 10000 >> ipcWaitRead
```
[the remark this answers is not in the document]
Comment (FinleyMcIlwaine) [reply test-grapesy/Test/Sanity/Disconnect.hs:144]: I agree, I will make this change as part of the PR

File: test-grapesy/Test/Util/RawTestServer.hs [hunk 7]
```diff
@@ -0,0 +1,110 @@
...
+  Raw test server
+
+  This allows us to simulate broken /servers/.
+-------------------------------------------------------------------------------}
+
+-- | Low-level test server
+--
+-- We bypass the entire grapesy machinery for constructing the server, for added
+-- flexibility. This allows us to mock broken deployments or run the server in
+-- another thread that we throw asynchronous exceptions to, for example.
```
[the remark this answers is not in the document]
Comment (FinleyMcIlwaine) [reply test-grapesy/Test/Util/RawTestServer.hs:31]: This is out of date, we no longer throw asynchronous exceptions to servers started by this

File: test-grapesy/Test/Util/RawTestServer.hs [hunk 8]
```diff
@@ -0,0 +1,110 @@
...
+--
+-- The grapesy client can auto reconnect when the server is not (yet) up and
+-- running, but to keep things simple, we just signal when the server is ready.
+-- This also allows us to avoid binding to a specific port in the tests (which
+-- might already be in use on the machine running the tests, leading to spurious
+-- test failures).
+rawTestServer :: IO (Maybe PortNumber) -> (PortNumber -> IO ()) -> HTTP2.Server -> IO ()
```
[the remark this answers is not in the document]
Comment (FinleyMcIlwaine) [reply test-grapesy/Test/Util/RawTestServer.hs:38]: I'll attempt to use `forkServer` and remove `rawTestServer`

File: test-grapesy/Test/Sanity/Disconnect.hs (hunk 6 above)
[the remark this answers is not in the document]
Comment (FinleyMcIlwaine) [reply test-grapesy/Test/Sanity/Disconnect.hs:144]: This will also make using pipes easier, so I'll try that again as well

File: test-grapesy/Test/Sanity/Disconnect.hs [hunk 9]
```diff
@@ -0,0 +1,288 @@
...
+      ( Client.withConnection def serverAddress $ \conn -> do
+          sum <$> mapConcurrently
+            (   Client.withRPC conn def (Proxy @Trivial')
+              . countUntil
+            )
+            predicates
+      )
+
+    -- All calls should have finished with a results of 'countTo', for both
+    -- clients
```
[the remark this answers is not in the document]
Comment (FinleyMcIlwaine) [reply test-grapesy/Test/Sanity/Disconnect.hs:115]: Correct, I'll emphasize that better

File: test-grapesy/Test/Sanity/Disconnect.hs (hunk 1 above)
Comment (FinleyMcIlwaine) [reply test-grapesy/Test/Sanity/Disconnect.hs:194]: Will abstract 🫡

File: test-grapesy/Test/Sanity/Exception.hs (hunk 2 above)
Comment (FinleyMcIlwaine) [reply test-grapesy/Test/Sanity/Exception.hs:14]: True, I'll add the server side properties

File: test-grapesy/Test/Sanity/Disconnect.hs [hunk 10]
```diff
@@ -0,0 +1,288 @@
...
+            \(_e :: Server.ClientDisconnected) ->
+              atomicModifyIORef' counter $ \n -> (n + 1, ())
+          )
+
+{-------------------------------------------------------------------------------
+  Auxiliary
+-------------------------------------------------------------------------------}
+
+foreign import ccall unsafe "kill" c_kill :: CInt -> CInt -> IO ()
+foreign import ccall unsafe "exit" c_exit :: CInt -> IO ()
```
[the remark this answers is not in the document]
Comment (FinleyMcIlwaine) [reply test-grapesy/Test/Sanity/Disconnect.hs:278]: `exitWith` translates to `throwIO`, so exception handling happens and the test fails. We need the immediate exit `c_exit`.

File: test-grapesy/Test/Sanity/Disconnect.hs (hunk 6 above)
[the remark this answers is not in the document]
Comment (FinleyMcIlwaine) [reply test-grapesy/Test/Sanity/Disconnect.hs]: I've made `ReconnectAfter` take a `Maybe Server` argument so reconnect policies can now specify different addresses for reconnection. Seems to work well in the tests in this PR so far. I did not end up going with the pipes. They introduce more complexity than this temporary file method, so I'm sticking with it for now. Up for more discussion on it though!

File: test-grapesy/Test/Sanity/Disconnect.hs (hunk 1 above)
Comment (FinleyMcIlwaine) [reply test-grapesy/Test/Sanity/Disconnect.hs:219]: Test steps are now described by a tiny DSL and interpreted, no more predicates or pure exceptions. Feels much cleaner.

File: src/Network/GRPC/Client/Connection.hs [hunk 11]
```diff
@@ -165,13 +166,18 @@ data ReconnectPolicy =
     -- connection), do not attempt to connect again.
     DontReconnect
 
-    -- | Reconnect after random delay after the IO action returns
+    -- | Reconnect to the (potentially different) server after the IO action
+    -- returns
+    --
+    -- If the 'Maybe' is 'Just', we'll attempt to reconnect to a server at the
+    -- new address. If 'Nothing', we'll attempt to connect to the original
+    -- server that 'withConnection' was given.
```
Comment (edsko) [inline src/Network/GRPC/Client/Connection.hs:174]: The documentation is entirely in line with the implementation, but on first reading I nonetheless misunderstood. I thought on `Nothing` we'd reconnect to the previous server we were connected to, but instead you choose to connect to the _initial_ server. I think both choices are defensible, not sure what the most sensible default is. Perhaps instead of a `Maybe` we should have 

```haskell
data ReconnectTo =
    ReconnectToPrev
  | ReconnectToOrig
  | ReconnectToNew Server
```

or something along these lines?

File: src/Network/GRPC/Client/Connection.hs [hunk 12]
```diff
@@ -165,13 +166,18 @@ data ReconnectPolicy =
     -- connection), do not attempt to connect again.
     DontReconnect
 
-    -- | Reconnect after random delay after the IO action returns
+    -- | Reconnect to the (potentially different) server after the IO action
+    -- returns
```
Comment (edsko) [inline src/Network/GRPC/Client/Connection.hs:170]: It might be worth explicitly pointing out that this can be used as a (poor-man's?) way to implement redundancy? Or are we worried that that particular man is _too_ poor? :thinking:

File: src/Network/GRPC/Client/Connection.hs [hunk 13]
```diff
@@ -378,11 +384,11 @@ stayConnected ::
...
   -> IO ()
-stayConnected connParams server connStateVar connOutOfScope =
-    loop (connReconnectPolicy connParams)
+stayConnected connParams initialServer connStateVar connOutOfScope = do
+    loop initialServer (connReconnectPolicy connParams)
   where
-    loop :: ReconnectPolicy -> IO ()
-    loop remainingReconnectPolicy = do
+    loop :: Server -> ReconnectPolicy -> IO ()
+    loop server remainingReconnectPolicy = do
```
Comment (edsko) [inline src/Network/GRPC/Client/Connection.hs:391]: Glad to see that the actual implementation was as clean as this :)

File: test-grapesy/Test/Sanity/Disconnect.hs (hunk 10 above)
[the remark this answers is not in the document]
Comment (edsko) [reply test-grapesy/Test/Sanity/Disconnect.hs:299]: Ah, I see, fair enough. Then let's add least add a comment here, because exiting the Haskell process this way also doesn't allow the RTS to shutdown cleanly. Of course, that's kind of the point here: this is modelling the server crashing for some reason.

File: test-grapesy/Test/Sanity/Exception.hs [hunk 14]
```diff
@@ -0,0 +1,189 @@
...
+        Binary.sendNextOutput @Word64 call $ succ n
+        incUntilFinal call
+      FinalElem n _ -> do
+        Binary.sendFinalOutput @Word64 call (succ n, NoMetadata)
+      NoMoreElems _ -> do
+        -- TODO: <https://github.com/well-typed/grapesy/issues/209>
+        --
+        -- We shouldn't need to handle this case, since our client never
+        -- explicitly sends 'NoMoreElems'. However, see discussion in the
+        -- ticket above.
```
Comment (edsko) [inline test-grapesy/Test/Sanity/Exception.hs:187]: Once the `http2` stuff is merged, this ticket can be closed right?

**Review by edsko — COMMENTED** [review]
Awesome, almost there I think :)

File: test-grapesy/Test/Sanity/Exception.hs (hunk 14 above)
Comment (edsko) [reply test-grapesy/Test/Sanity/Exception.hs:187]: We can do that independently from this PR, of course. Remind me, do we rely on any other recent `http2`/`http-semantics` changes for this PR to go through?

**Review by edsko — APPROVED** [review]
Approving in anticipation of the changes discussed above.
